apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080

    - name: ubuntu-container
      image: ubuntu