apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: data-processor
      image: data-processor
  nodeSelector:
    size: Large

# We need to label the nodes before applying node selector

# Command to label the node

# kubectl label nodes <node-name> <label-key>:<label-value>

# Sample Example

# kubectl label nodes controlplane size=Large