apiVersion: v1
kind: Pod
metadata:
  name: simple-webcolor-app
spec:
  containers:
    - name: simple-webcolor-app
      image: simple-webcolor-app
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config